### ISSUE TITLE
ModuleNotFoundError: No module named 'ss2'

### ISSUE THREAD

**Issue by 15102339474** [inside-openflow/simpleswitch2#2]
执行ryu-manager ss2.core时，
提示没有ss2这个模块，我不太明白在simpleswitch2-0.1.2-noacl这个目录下，没有ss2.core这个执行文件啊，ss2不是一个目录吗

**Comment by leonexis** [comment]
I'm afraid that I had to rely on Google Translate so my understanding may not be correct, but from what I could gather, this might be a duplicate of #1. Please ensure that the local path is is in `PYTHONPATH`.
